extend type Mutation {
  """
  ✨ Insert a single `AiDiscoveryLog` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiDiscoveryLog_insert(
    """
    Data object to insert into the table.
    """
    data: AiDiscoveryLog_Data!
  ): AiDiscoveryLog_KeyOutput! @fdc_generated(from: "AiDiscoveryLog", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ModificationRequest` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  modificationRequest_insert(
    """
    Data object to insert into the table.
    """
    data: ModificationRequest_Data!
  ): ModificationRequest_KeyOutput! @fdc_generated(from: "ModificationRequest", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `NewArrival` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newArrival_insert(
    """
    Data object to insert into the table.
    """
    data: NewArrival_Data!
  ): NewArrival_KeyOutput! @fdc_generated(from: "NewArrival", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `NewsArticle` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newsArticle_insert(
    """
    Data object to insert into the table.
    """
    data: NewsArticle_Data!
  ): NewsArticle_KeyOutput! @fdc_generated(from: "NewsArticle", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ReviewComment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reviewComment_insert(
    """
    Data object to insert into the table.
    """
    data: ReviewComment_Data!
  ): ReviewComment_KeyOutput! @fdc_generated(from: "ReviewComment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ReviewLike` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reviewLike_insert(
    """
    Data object to insert into the table.
    """
    data: ReviewLike_Data!
  ): ReviewLike_KeyOutput! @fdc_generated(from: "ReviewLike", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Spirit` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  spirit_insert(
    """
    Data object to insert into the table.
    """
    data: Spirit_Data!
  ): Spirit_KeyOutput! @fdc_generated(from: "Spirit", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `SpiritReview` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  spiritReview_insert(
    """
    Data object to insert into the table.
    """
    data: SpiritReview_Data!
  ): SpiritReview_KeyOutput! @fdc_generated(from: "SpiritReview", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `UserCabinet` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userCabinet_insert(
    """
    Data object to insert into the table.
    """
    data: UserCabinet_Data!
  ): UserCabinet_KeyOutput! @fdc_generated(from: "UserCabinet", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `WorldCupResult` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  worldCupResult_insert(
    """
    Data object to insert into the table.
    """
    data: WorldCupResult_Data!
  ): WorldCupResult_KeyOutput! @fdc_generated(from: "WorldCupResult", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AiDiscoveryLog` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  aiDiscoveryLog_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AiDiscoveryLog_Data!]!
  ): [AiDiscoveryLog_KeyOutput!]! @fdc_generated(from: "AiDiscoveryLog", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ModificationRequest` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  modificationRequest_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ModificationRequest_Data!]!
  ): [ModificationRequest_KeyOutput!]! @fdc_generated(from: "ModificationRequest", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `NewArrival` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newArrival_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [NewArrival_Data!]!
  ): [NewArrival_KeyOutput!]! @fdc_generated(from: "NewArrival", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `NewsArticle` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  newsArticle_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [NewsArticle_Data!]!
  ): [NewsArticle_KeyOutput!]! @fdc_generated(from: "NewsArticle", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ReviewComment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reviewComment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ReviewComment_Data!]!
  ): [ReviewComment_KeyOutput!]! @fdc_generated(from: "ReviewComment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ReviewLike` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reviewLike_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ReviewLike_Data!]!
  ): [ReviewLike_KeyOutput!]! @fdc_generated(from: "ReviewLike", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Spirit` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  spirit_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Spirit_Data!]!
  ): [Spirit_KeyOutput!]! @fdc_generated(from: "Spirit", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `SpiritReview` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  spiritReview_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [SpiritReview_Data!]!
  ): [SpiritReview_KeyOutput!]! @fdc_generated(from: "SpiritReview", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `UserCabinet` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  userCabinet_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [UserCabinet_Data!]!
  ): [UserCabinet_KeyOutput!]! @fdc_generated(from: "UserCabinet", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `WorldCupResult` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  worldCupResult_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [WorldCupResult_Data!]!
  ): [WorldCupResult_KeyOutput!]! @fdc_generated(from: "WorldCupResult", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AiDiscoveryLog` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiDiscoveryLog`.
  """
  aiDiscoveryLog_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AiDiscoveryLog_Data!
  ): AiDiscoveryLog_KeyOutput! @fdc_generated(from: "AiDiscoveryLog", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ModificationRequest` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ModificationRequest`.
  """
  modificationRequest_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ModificationRequest_Data!
  ): ModificationRequest_KeyOutput! @fdc_generated(from: "ModificationRequest", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `NewArrival` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `NewArrival`.
  """
  newArrival_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: NewArrival_Data!
  ): NewArrival_KeyOutput! @fdc_generated(from: "NewArrival", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `NewsArticle` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `NewsArticle`.
  """
  newsArticle_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: NewsArticle_Data!
  ): NewsArticle_KeyOutput! @fdc_generated(from: "NewsArticle", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ReviewComment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReviewComment`.
  """
  reviewComment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ReviewComment_Data!
  ): ReviewComment_KeyOutput! @fdc_generated(from: "ReviewComment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ReviewLike` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReviewLike`.
  """
  reviewLike_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ReviewLike_Data!
  ): ReviewLike_KeyOutput! @fdc_generated(from: "ReviewLike", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Spirit` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Spirit`.
  """
  spirit_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Spirit_Data!
  ): Spirit_KeyOutput! @fdc_generated(from: "Spirit", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `SpiritReview` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SpiritReview`.
  """
  spiritReview_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: SpiritReview_Data!
  ): SpiritReview_KeyOutput! @fdc_generated(from: "SpiritReview", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `UserCabinet` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserCabinet`.
  """
  userCabinet_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: UserCabinet_Data!
  ): UserCabinet_KeyOutput! @fdc_generated(from: "UserCabinet", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `WorldCupResult` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorldCupResult`.
  """
  worldCupResult_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: WorldCupResult_Data!
  ): WorldCupResult_KeyOutput! @fdc_generated(from: "WorldCupResult", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AiDiscoveryLog` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AiDiscoveryLog`.
  """
  aiDiscoveryLog_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AiDiscoveryLog_Data!]!
  ): [AiDiscoveryLog_KeyOutput!]! @fdc_generated(from: "AiDiscoveryLog", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ModificationRequest` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ModificationRequest`.
  """
  modificationRequest_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ModificationRequest_Data!]!
  ): [ModificationRequest_KeyOutput!]! @fdc_generated(from: "ModificationRequest", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `NewArrival` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `NewArrival`.
  """
  newArrival_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [NewArrival_Data!]!
  ): [NewArrival_KeyOutput!]! @fdc_generated(from: "NewArrival", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `NewsArticle` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `NewsArticle`.
  """
  newsArticle_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [NewsArticle_Data!]!
  ): [NewsArticle_KeyOutput!]! @fdc_generated(from: "NewsArticle", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ReviewComment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReviewComment`.
  """
  reviewComment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ReviewComment_Data!]!
  ): [ReviewComment_KeyOutput!]! @fdc_generated(from: "ReviewComment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ReviewLike` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReviewLike`.
  """
  reviewLike_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ReviewLike_Data!]!
  ): [ReviewLike_KeyOutput!]! @fdc_generated(from: "ReviewLike", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Spirit` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Spirit`.
  """
  spirit_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Spirit_Data!]!
  ): [Spirit_KeyOutput!]! @fdc_generated(from: "Spirit", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `SpiritReview` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `SpiritReview`.
  """
  spiritReview_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [SpiritReview_Data!]!
  ): [SpiritReview_KeyOutput!]! @fdc_generated(from: "SpiritReview", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `UserCabinet` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `UserCabinet`.
  """
  userCabinet_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [UserCabinet_Data!]!
  ): [UserCabinet_KeyOutput!]! @fdc_generated(from: "UserCabinet", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `WorldCupResult` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `WorldCupResult`.
  """
  worldCupResult_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [WorldCupResult_Data!]!
  ): [WorldCupResult_KeyOutput!]! @fdc_generated(from: "WorldCupResult", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AiDiscoveryLog` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AiDiscoveryLog` or `null` if not found.
  """
  aiDiscoveryLog_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AiDiscoveryLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiDiscoveryLog_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AiDiscoveryLog_Data!
  ): AiDiscoveryLog_KeyOutput @fdc_generated(from: "AiDiscoveryLog", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ModificationRequest` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ModificationRequest` or `null` if not found.
  """
  modificationRequest_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: ModificationRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModificationRequest_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ModificationRequest_Data!
  ): ModificationRequest_KeyOutput @fdc_generated(from: "ModificationRequest", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `NewArrival` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `NewArrival` or `null` if not found.
  """
  newArrival_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewArrival_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewArrival_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: NewArrival_Data!
  ): NewArrival_KeyOutput @fdc_generated(from: "NewArrival", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `NewsArticle` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `NewsArticle` or `null` if not found.
  """
  newsArticle_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewsArticle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewsArticle_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: NewsArticle_Data!
  ): NewsArticle_KeyOutput @fdc_generated(from: "NewsArticle", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ReviewComment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ReviewComment` or `null` if not found.
  """
  reviewComment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReviewComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewComment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ReviewComment_Data!
  ): ReviewComment_KeyOutput @fdc_generated(from: "ReviewComment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ReviewLike` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ReviewLike` or `null` if not found.
  """
  reviewLike_update(
    """
    The key used to identify the object.
    """
    key: ReviewLike_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewLike_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ReviewLike_Data!
  ): ReviewLike_KeyOutput @fdc_generated(from: "ReviewLike", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Spirit` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Spirit` or `null` if not found.
  """
  spirit_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Spirit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Spirit_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Spirit_Data!
  ): Spirit_KeyOutput @fdc_generated(from: "Spirit", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `SpiritReview` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `SpiritReview` or `null` if not found.
  """
  spiritReview_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SpiritReview_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SpiritReview_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: SpiritReview_Data!
  ): SpiritReview_KeyOutput @fdc_generated(from: "SpiritReview", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `UserCabinet` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `UserCabinet` or `null` if not found.
  """
  userCabinet_update(
    """
    The key used to identify the object.
    """
    key: UserCabinet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserCabinet_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: UserCabinet_Data!
  ): UserCabinet_KeyOutput @fdc_generated(from: "UserCabinet", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `WorldCupResult` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `WorldCupResult` or `null` if not found.
  """
  worldCupResult_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorldCupResult_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorldCupResult_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: WorldCupResult_Data!
  ): WorldCupResult_KeyOutput @fdc_generated(from: "WorldCupResult", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AiDiscoveryLog` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  aiDiscoveryLog_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AiDiscoveryLog_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AiDiscoveryLog_Data!
  ): Int! @fdc_generated(from: "AiDiscoveryLog", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ModificationRequest` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  modificationRequest_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ModificationRequest_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ModificationRequest_Data!
  ): Int! @fdc_generated(from: "ModificationRequest", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `NewArrival` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  newArrival_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: NewArrival_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: NewArrival_Data!
  ): Int! @fdc_generated(from: "NewArrival", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `NewsArticle` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  newsArticle_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: NewsArticle_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: NewsArticle_Data!
  ): Int! @fdc_generated(from: "NewsArticle", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ReviewComment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  reviewComment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ReviewComment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ReviewComment_Data!
  ): Int! @fdc_generated(from: "ReviewComment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ReviewLike` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  reviewLike_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ReviewLike_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ReviewLike_Data!
  ): Int! @fdc_generated(from: "ReviewLike", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Spirit` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  spirit_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Spirit_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Spirit_Data!
  ): Int! @fdc_generated(from: "Spirit", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `SpiritReview` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  spiritReview_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: SpiritReview_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: SpiritReview_Data!
  ): Int! @fdc_generated(from: "SpiritReview", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `UserCabinet` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  userCabinet_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: UserCabinet_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: UserCabinet_Data!
  ): Int! @fdc_generated(from: "UserCabinet", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `WorldCupResult` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  worldCupResult_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: WorldCupResult_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: WorldCupResult_Data!
  ): Int! @fdc_generated(from: "WorldCupResult", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AiDiscoveryLog` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  aiDiscoveryLog_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AiDiscoveryLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiDiscoveryLog_FirstRow
  ): AiDiscoveryLog_KeyOutput @fdc_generated(from: "AiDiscoveryLog", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ModificationRequest` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  modificationRequest_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: ModificationRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModificationRequest_FirstRow
  ): ModificationRequest_KeyOutput @fdc_generated(from: "ModificationRequest", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `NewArrival` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  newArrival_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewArrival_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewArrival_FirstRow
  ): NewArrival_KeyOutput @fdc_generated(from: "NewArrival", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `NewsArticle` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  newsArticle_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewsArticle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewsArticle_FirstRow
  ): NewsArticle_KeyOutput @fdc_generated(from: "NewsArticle", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ReviewComment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  reviewComment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReviewComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewComment_FirstRow
  ): ReviewComment_KeyOutput @fdc_generated(from: "ReviewComment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ReviewLike` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  reviewLike_delete(
    """
    The key used to identify the object.
    """
    key: ReviewLike_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewLike_FirstRow
  ): ReviewLike_KeyOutput @fdc_generated(from: "ReviewLike", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Spirit` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  spirit_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Spirit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Spirit_FirstRow
  ): Spirit_KeyOutput @fdc_generated(from: "Spirit", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `SpiritReview` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  spiritReview_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SpiritReview_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SpiritReview_FirstRow
  ): SpiritReview_KeyOutput @fdc_generated(from: "SpiritReview", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `UserCabinet` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  userCabinet_delete(
    """
    The key used to identify the object.
    """
    key: UserCabinet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserCabinet_FirstRow
  ): UserCabinet_KeyOutput @fdc_generated(from: "UserCabinet", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `WorldCupResult` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  worldCupResult_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorldCupResult_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorldCupResult_FirstRow
  ): WorldCupResult_KeyOutput @fdc_generated(from: "WorldCupResult", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AiDiscoveryLog` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  aiDiscoveryLog_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AiDiscoveryLog_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AiDiscoveryLog", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ModificationRequest` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  modificationRequest_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ModificationRequest_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ModificationRequest", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `NewArrival` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  newArrival_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: NewArrival_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "NewArrival", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `NewsArticle` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  newsArticle_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: NewsArticle_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "NewsArticle", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ReviewComment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  reviewComment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ReviewComment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ReviewComment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ReviewLike` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  reviewLike_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ReviewLike_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ReviewLike", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Spirit` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  spirit_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Spirit_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Spirit", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `SpiritReview` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  spiritReview_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: SpiritReview_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "SpiritReview", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `UserCabinet` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  userCabinet_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: UserCabinet_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "UserCabinet", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `WorldCupResult` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  worldCupResult_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: WorldCupResult_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "WorldCupResult", purpose: DELETE_MULTIPLE)
}
