extend type Query {
  """
  ✨ Look up a single `AiDiscoveryLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aiDiscoveryLog(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AiDiscoveryLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AiDiscoveryLog_FirstRow
  ): AiDiscoveryLog @fdc_generated(from: "AiDiscoveryLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ModificationRequest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  modificationRequest(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: ModificationRequest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModificationRequest_FirstRow
  ): ModificationRequest @fdc_generated(from: "ModificationRequest", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `NewArrival` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  newArrival(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewArrival_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewArrival_FirstRow
  ): NewArrival @fdc_generated(from: "NewArrival", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `NewsArticle` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  newsArticle(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: NewsArticle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: NewsArticle_FirstRow
  ): NewsArticle @fdc_generated(from: "NewsArticle", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ReviewComment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reviewComment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReviewComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewComment_FirstRow
  ): ReviewComment @fdc_generated(from: "ReviewComment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ReviewLike` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reviewLike(
    """
    The key used to identify the object.
    """
    key: ReviewLike_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReviewLike_FirstRow
  ): ReviewLike @fdc_generated(from: "ReviewLike", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Spirit` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  spirit(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Spirit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Spirit_FirstRow
  ): Spirit @fdc_generated(from: "Spirit", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SpiritReview` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  spiritReview(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SpiritReview_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SpiritReview_FirstRow
  ): SpiritReview @fdc_generated(from: "SpiritReview", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserCabinet` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userCabinet(
    """
    The key used to identify the object.
    """
    key: UserCabinet_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserCabinet_FirstRow
  ): UserCabinet @fdc_generated(from: "UserCabinet", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `WorldCupResult` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  worldCupResult(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: WorldCupResult_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: WorldCupResult_FirstRow
  ): WorldCupResult @fdc_generated(from: "WorldCupResult", purpose: QUERY_SINGLE)
  """
  ✨ List `AiDiscoveryLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aiDiscoveryLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: AiDiscoveryLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AiDiscoveryLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AiDiscoveryLog_Having
  ): [AiDiscoveryLog!]! @fdc_generated(from: "AiDiscoveryLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ModificationRequest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  modificationRequests(
    """
    Filter condition to narrow down the query results.
    """
    where: ModificationRequest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModificationRequest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModificationRequest_Having
  ): [ModificationRequest!]! @fdc_generated(from: "ModificationRequest", purpose: QUERY_MULTIPLE)
  """
  ✨ List `NewArrival` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  newArrivals(
    """
    Filter condition to narrow down the query results.
    """
    where: NewArrival_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NewArrival_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NewArrival_Having
  ): [NewArrival!]! @fdc_generated(from: "NewArrival", purpose: QUERY_MULTIPLE)
  """
  ✨ List `NewsArticle` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  newsArticles(
    """
    Filter condition to narrow down the query results.
    """
    where: NewsArticle_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [NewsArticle_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: NewsArticle_Having
  ): [NewsArticle!]! @fdc_generated(from: "NewsArticle", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ReviewComment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reviewComments(
    """
    Filter condition to narrow down the query results.
    """
    where: ReviewComment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ReviewComment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ReviewComment_Having
  ): [ReviewComment!]! @fdc_generated(from: "ReviewComment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ReviewLike` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reviewLikes(
    """
    Filter condition to narrow down the query results.
    """
    where: ReviewLike_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ReviewLike_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ReviewLike_Having
  ): [ReviewLike!]! @fdc_generated(from: "ReviewLike", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Spirit` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  spirits(
    """
    Filter condition to narrow down the query results.
    """
    where: Spirit_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Spirit_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Spirit_Having
  ): [Spirit!]! @fdc_generated(from: "Spirit", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SpiritReview` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  spiritReviews(
    """
    Filter condition to narrow down the query results.
    """
    where: SpiritReview_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SpiritReview_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SpiritReview_Having
  ): [SpiritReview!]! @fdc_generated(from: "SpiritReview", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserCabinet` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userCabinets(
    """
    Filter condition to narrow down the query results.
    """
    where: UserCabinet_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserCabinet_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserCabinet_Having
  ): [UserCabinet!]! @fdc_generated(from: "UserCabinet", purpose: QUERY_MULTIPLE)
  """
  ✨ List `WorldCupResult` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  worldCupResults(
    """
    Filter condition to narrow down the query results.
    """
    where: WorldCupResult_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [WorldCupResult_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: WorldCupResult_Having
  ): [WorldCupResult!]! @fdc_generated(from: "WorldCupResult", purpose: QUERY_MULTIPLE)
}
