import json
import os
import datetime

# Configuration
INPUT_FILE = r'lib/db/ingested-data.json'
OUTPUT_FILE = r'data/migration.sql'

def escape_sql_string(value):
    if value is None:
        return 'NULL'
    if isinstance(value, str):
        # Escape single quotes
        return "'" + value.replace("'", "''") + "'"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bool):
        return '1' if value else '0'
    return 'NULL'

def main():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Input file not found: {INPUT_FILE}")
        return

    print(f"Reading {INPUT_FILE}...")
    try:
        with open(INPUT_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Failed to load JSON: {e}")
        return

    if not isinstance(data, list):
        print("Error: JSON root must be a list")
        return

    print(f"Found {len(data)} items. Generating SQL...")

    sql_statements = []
    
    # Optional: Clear table execution
    # sql_statements.append("DELETE FROM spirits;") 

    for item in data:
        # Extract fields matching schema
        id_val = item.get('id')
        name = item.get('name')
        distillery = item.get('distillery') or ''
        bottler = item.get('bottler')
        abv = item.get('abv')
        volume = item.get('volume')
        category = item.get('category') or 'Uncategorized'
        subcategory = item.get('subcategory')
        country = item.get('country') or 'Unknown'
        region = item.get('region')
        image_url = item.get('imageUrl')
        thumbnail_url = item.get('thumbnailUrl')
        source = item.get('source')
        external_id = item.get('externalId')
        status = item.get('status') or 'RAW'
        is_published = item.get('isPublished', False)
        is_reviewed = item.get('isReviewed', False)
        reviewed_by = item.get('reviewedBy')
        reviewed_at = item.get('reviewedAt')
        
        # Handle metadata JSON
        metadata = item.get('metadata', {})
        metadata_json = json.dumps(metadata, ensure_ascii=False)
        
        # Dates
        created_at = item.get('createdAt') or datetime.datetime.now().isoformat()
        updated_at = item.get('updatedAt') or datetime.datetime.now().isoformat()

        # Build INSERT
        columns = [
            'id', 'name', 'distillery', 'bottler', 'abv', 'volume', 
            'category', 'subcategory', 'country', 'region', 
            'image_url', 'thumbnail_url', 'source', 'external_id', 
            'status', 'is_published', 'is_reviewed', 'reviewed_by', 'reviewed_at',
            'metadata', 'created_at', 'updated_at'
        ]
        
        values = [
            escape_sql_string(id_val),
            escape_sql_string(name),
            escape_sql_string(distillery),
            escape_sql_string(bottler),
            escape_sql_string(abv),
            escape_sql_string(volume),
            escape_sql_string(category),
            escape_sql_string(subcategory),
            escape_sql_string(country),
            escape_sql_string(region),
            escape_sql_string(image_url),
            escape_sql_string(thumbnail_url),
            escape_sql_string(source),
            escape_sql_string(external_id),
            escape_sql_string(status),
            escape_sql_string(is_published),
            escape_sql_string(is_reviewed),
            escape_sql_string(reviewed_by),
            escape_sql_string(reviewed_at),
            escape_sql_string(metadata_json),
            escape_sql_string(created_at),
            escape_sql_string(updated_at)
        ]

        stmt = f"INSERT OR REPLACE INTO spirits ({', '.join(columns)}) VALUES ({', '.join(values)});"
        sql_statements.append(stmt)

    # Write output
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("-- Migration Script Generated by antigravity\n")
        f.write("\n".join(sql_statements))
        f.write("\n")

    print(f"Successfully generated {OUTPUT_FILE} with {len(sql_statements)} statements.")

if __name__ == "__main__":
    main()
